"""Add invite_font to Party model

Revision ID: 491a3e67287b
Revises: ab5f97567bec
Create Date: 2025-07-07 01:51:28.636888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491a3e67287b'
down_revision = 'ab5f97567bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_font', sa.String(length=100), nullable=True))

    op.execute("UPDATE party SET invite_font = 'Montserrat-Regular' WHERE invite_font IS NULL")

    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.alter_column('invite_font',
               existing_type=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party', schema=None) as batch_op:
        batch_op.drop_column('invite_font')
    # ### end Alembic commands ###